export const SET_RPANELWIDTH = 'SET_RPANELWIDTH';
export const SET_SHOWFLAG = 'SET_SHOWFLAG';
export const SET_HIDETIMEBAR = 'SET_HIDETIMEBAR';
export const MENU_HIDE = 'MENU_HIDE';
export const SET_COMMONTITLE = 'SET_COMMONTITLE';
export const SET_TITLETIME = 'SET_TITLETIME';
export const SET_HIDETITLETIME = 'SET_HIDETITLETIME';